name: Assemble project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build library
        run: ./gradlew :parsely:assembleDebug
      - name: Build example app
        run: ./gradlew :example:assembleDebug
      - name: Android Lint
        run: ./gradlew lintDebug
      - name: Validate Maven publication
        run: ./gradlew :parsely:publishReleasePublicationToMavenLocal
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ~/.m2/repository/com/parsely/parsely/*
